### ISSUE TITLE
make run - 

### ISSUE THREAD

**Issue by nuke3** [nuke3/ChainSign#1] opened 2017-02-28 21:58 UTC
```
$ make run
python chainsign.py
Traceback (most recent call last):
  File "chainsign.py", line 64, in <module>
    class MainWindow(QtGui.QMainWindow, mainwindow.Ui_MainWindow):
AttributeError: 'module' object has no attribute 'Ui_MainWindow'
Makefile:7: polecenia dla obiektu 'run' nie powiodły się
make: *** [run] Błąd 1
```

**Comment by Informatic** [comment] 2017-02-28 23:37
This seems to be caused by previous call to `pyside-uic` failing and creation of empty `gui/mainwindow.py` file. This has been fixed in f1a843e, so that no empty file should be created on failure now.

**Closed as completed by Informatic** 2017-02-28 23:37 UTC
